spring:
  main:
    banner-mode: off
  datasource:
    url: ${REPORT_DATASOURCE_URL:jdbc:h2:mem:cdr_db}
    username: ${REPORT_DATASOURCE_USERNAME:user}
    password: ${REPORT_DATASOURCE_PASSWORD:password}
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10  # Максимальное количество соединений в пуле
      minimum-idle: 2        # Минимальное количество неиспользуемых соединений
      idle-timeout: 30000    # Время ожидания в миллисекундах перед закрытием неиспользуемого соединения
      connection-timeout: 30000  # Время ожидания в миллисекундах при получении соединения из пула
      max-lifetime: 1800000   # Максимальное время жизни соединения в миллисекундах
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: ${REPORT_RABBITMQ_HOST:localhost}
    port: ${REPORT_RABBITMQ_PORT:5672}
    username: ${REPORT_RABBITMQ_USERNAME:test}
    password: ${REPORT_RABBITMQ_PASSWORD:test}

rabbitmq:
  exchange-name:
      cdr:
        send:
          name: ${RABBITMQ_EXCHANGE_NAME_REPORT_CDR_SEND:cdr.report.send}
  queue:
    cdr:
      name: ${RABBITMQ_QUEUE_CDR_NAME:cdr.queue}
  routing-key:
    cdr:
      name: ${RABBITMQ_ROUTING_KEY_CDR_NAME:cdr_record}

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: DEBUG