server:
  port: ${REPORT_BIND_PORT:8080}
api:
  prefix:
    public: ${REPORT_WEB_PREFIX_PUBLIC:/api/report}

app:
  reports-dir: reports

spring:
  main:
    banner-mode: off
  datasource:
    url: ${REPORT_DATASOURCE_URL:jdbc:h2:mem:cdr_db}
    username: ${REPORT_DATASOURCE_USERNAME:user}
    password: ${REPORT_DATASOURCE_PASSWORD:password}
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10  # Максимальное количество соединений в пуле
      minimum-idle: 2        # Минимальное количество неиспользуемых соединений
      idle-timeout: 30000    # Время ожидания в миллисекундах перед закрытием неиспользуемого соединения
      connection-timeout: 30000  # Время ожидания в миллисекундах при получении соединения из пула
      max-lifetime: 1800000   # Максимальное время жизни соединения в миллисекундах
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: DEBUG